# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PROJECTROOT="<%= @root %>"
PHPBIN=$PROJECTROOT/vendor/bin

PATH=$PATH:$HOME/.local/bin:$HOME/bin
PATH=$PATH:$PHPBIN

export PATH
